# Standard labeler configuration file for GitHub Actions
# Apply labels based on file path patterns

labels:
  bug:
    - '**/*.bug'   # Example pattern for bugs
    - 'src/errors/**' # Apply for files related to errors

  feature:
    - '**/*.feature' # Example pattern for features
    - 'src/features/**'

  documentation:
    - '**/*.md'  # Apply for Markdown files
    - 'docs/**'  # Apply for documentation folder

  test:
    - '**/*.test.*'  # Apply for test files
    - 'tests/**'     # Apply for test directories

  refactor:
    - 'src/refactor/**'  # Apply for refactoring-related changes
