export enum TimeRangeConstants {
  TODAY = "TODAY",
  LAST_7_DAYS = "LAST_7_DAYS",
  LAST_30_DAYS = "LAST_30_DAYS",
  LAST_90_DAYS = "LAST_90_DAYS",
  LAST_180_DAYS = "LAST_180_DAYS",
  LAST_365_DAYS = "LAST_365_DAYS"
}
